server:
  port: 9000
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  # 忽略真实的服务名称实例访问，是一个Set集合，可以指定多个，取消全部使用 "*"即可
  ignored-services:
    - "*"

  routes:
    #    参数key结构： zuul.routes.customName.path=xxx
    service-userloginprovider:
      path: /userloginprovider/**
      # 参数key结构： zuul.routes.customName.url=xxx
      # url用于配置符合path的请求路径路由到的服务地址。
      url: http://localhost:7777/
      serviceId: service-buyer-provider

    service-userloginconsumer:
      path: /userloginconsumer/**
      # 参数key结构： zuul.routes.customName.url=xxx
      # url用于配置符合path的请求路径路由到的服务地址。
      url: http://localhost:7778/
      serviceId: service-buyer-consumer

    service-shopper-consumer:
      path: /shopperConsumer/**
      # 参数key结构： zuul.routes.customName.url=xxx
      # url用于配置符合path的请求路径路由到的服务地址。
      url: http://localhost:8091/
      serviceId: service-shopper-consumer

    service-shopper-provider:
      path: /shopperProvider/**
      # 参数key结构： zuul.routes.customName.url=xxx
      # url用于配置符合path的请求路径路由到的服务地址。
      url: http://localhost:8081/
      serviceId: service-shopper-provider

    service-shoppingcartprovider:
      path: /shoppingcartprovider/**
      url: http://localhost:8082/
      serviceId: service-shopping-cart-provider

    service-order-provider:
      path: /orderprovider/**
      url: http://localhost:7887/
      serviceId: service-order-provider

    service-order-consumer:
      path: /orderconsumer/**
      url: http://localhost:7889/
      serviceId: service-order-consumer

  prefix: /EJS
  add-host-header: true
