spring:
  application:
    name: service-buyer-provider    #\u8FD9\u4E00\u9879\u672C\u6765\u5728config\u4E2D
  datasource:
    #   \u6570\u636E\u6E90\u57FA\u672C\u914D\u7F6E
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ejs?characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    mvc:
      format:
        date: yyyy-MM-dd
      #\u6B64\u65F6\u4F7F\u7528restful\u98CE\u683Cput\u65B9\u6CD5\u65B9\u53EF\u63D0\u4EA4
      hiddenmethod:
        filter:
          enabled: true
          #config \u76F8\u5173
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: SERVICE-CONFIG-SERVER
#      fail-fast: true
#    profiles:
#      active: dev
mybatis:
      # \u6307\u5B9Asql\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
  mapper-locations: classpath:mybatis/mapper/*.xml
      # \u6307\u5B9A\u5168\u5C40\u914D\u7F6E\u6587\u4EF6\u4F4D\u7F6E
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.cebbank.buyer_provider.common.pojo
  #
  #\u4EE5\u4E0B\u672C\u6765\u5728config\u4E2D
server:
  port: 7777
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/