server:
  port: 8080
#  servlet:
#    context-path: /elsearch
#    jsp:
#      init-parameters:
#        development: true

spring:
  data:
    elasticsearch:
      rest:
        uris: 192.168.34.130:9300
#      cluster-nodes: 192.168.34.130:9300
      repositories:
        enabled: true